# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: "innovea.tech's notes by Sébastien Attia"
description: "Thoughts, stories and ideas on Machine Learning and Programming."

short_url: 'notes.innovea.tech/'
google_analytics: UA-78888028-2
disqus: innovea
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Required for jekyll-sitemap
url: "https://notes.innovea.tech"

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate, jekyll-sitemap]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: sebastien-attia
repo: sebastien-attia-notes
branch: master
relative_source: /
destination: _site/
production_url:  https://notes.innovea.tech/
source_url:  https://github.com/sebastien-attia/sebastien-attia-notes/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
